server:
  port: 8003
spring:
  application:
    name: vodService
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 4c3ca9cf-4c8d-47cc-a41c-6b8f9fd3e5f5

