server:
  port: 8008
spring:
  application:
    name: statisticsService
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 4c3ca9cf-4c8d-47cc-a41c-6b8f9fd3e5f5
feign:
  hystrix:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDeleted
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    root: info
