server:
  port: 8002
spring:
  application:
    name: service-oss
  profiles:
    active: dev

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou-internal.aliyuncs.com
      keyId: LTAI5tRaTHxgfk81RhqjqXMB
      keySecret: si9xFiMIiKWuXFYMYVDfvGqeE4BPKW
      bucketName: guli-edu-sakanal
